
name: Publish Slack Repo
on: 
  push:
    branches:
      - slack-test
jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: publish:slack
        uses: bitprj/push-subdir@0.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: Slack-Apps emsesc Bitcamp-Slack main
